name: Deploy Azure Function App to Azure

on:
  push:
    branches:
      - Azure-function-app  # Trigger on pushes to this branch
  pull_request:
    branches:
      - Azure-function-app  # Trigger on pull requests targeting this branch
  workflow_dispatch:  # Allow manual triggering of the workflow
env:
  AZURE_FUNCTIONAPP_NAME: 'fnapp3101'    # Replace with your Function App name
  AZURE_RESOURCE_GROUP: 'appfntest3101-rg'   # Replace with your Resource Group name
  #FUNCTION_APP_PACKAGE_PATH: './app.zip'     # Path to your ZIP package

jobs:
  deploy-function-app:
    runs-on: [self-hosted, self-hosted-linux]  # Using a self-hosted Linux runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Adjust to your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Create ZIP package
    - name: Create ZIP Package
      run: |
        zip -r functionapp.zip . -x '*.git*' '*.venv*' '.vscode/*' 'local.settings.json'

    # # Step 5: Set up Azure CLI
    # - name: Set up Azure CLI
    #   uses: azure/CLI@v2

    # Step 6: Log in to Azure using Service Principal
    - name: Log in to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.ARM_CLIENT_ID }} \
          --password ${{ secrets.ARM_CLIENT_SECRET }} \
          --tenant ${{ secrets.ARM_TENANT_ID }}
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    # List directory to check ZIP existence
    - name: List directory contents
      run: ls -alh

      # Deploy ZIP to Azure
    - name: Deploy ZIP Package to Azure Function App
      run: |
          az functionapp show --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src ./functionapp.zip  # Adjust if necessary
